ya_token     = ""
ya_cloud_id  = "b1gthe1naa936dn511am"
ya_folder_id = "b1gogcvb32hqskgu5trk"
ya_region = "ru-central1-a"
cluster_version  = "1.21"
cluster_name = "test-kuber"
cluster_release_channel = "STABLE"
network_policy_provider = "CALICO"