apiVersion: v1
kind: Namespace
metadata:
  name: testapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp-deploy
  namespace: testapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testapp-deploy
  template:
    metadata:
      name: testapp-deploy
      labels:
        app: testapp-deploy
    spec:
      containers:
      - name: testapp-deploy
        image: murzinvit/site:latest
        ports:
        - name: testapp-deploy
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: testapp-svc
  namespace: testapp
  labels:
    app: testapp-svc
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: testapp-deploy